### ISSUE TITLE
On homepage, the locations is wrong!

### ISSUE THREAD

**Issue by nybakk1** [danielakl/S-Authentication#1]
Hello.

According to the homepage we have offices in Antarctica, this is wrong!
Please fix

Regards,
HR

**Comment by rsylthe** [comment]
Hello @nybakk1 
We are aware of this bug. We have yet to implement a location tracker to our website, so the homepage will select a random location.

Regards,
IT Crew

**Comment by nybakk1** [comment]
I am not happy about this. But OK, I will open an office in Antarctica.

Regards, 
HR

**Comment by kristofferarn** [comment]
level 3 software engineer looking for job in Antarctica! Please dm for more info. Thanks :)
